service: hall-e-api
frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs20.x
  architecture: arm64
  memorySize: 512
  timeout: 15
  httpApi: { cors: true }
  environment:
    NODE_OPTIONS: '--enable-source-maps'
    SECRETS_MANAGER_ARN: ${env:SECRETS_MANAGER_ARN}
    SECRET_MONGO_KEY: MONGODB_URI
  iam:
    role:
      statements:
        - Effect: Allow
          Action: secretsmanager:GetSecretValue
          Resource: ${env:SECRETS_MANAGER_ARN}

functions:
  api:
    handler: src/aws/apiHandler.http
    events:
      - httpApi: 'GET /health'
      - httpApi:
          method: ANY
          path: /{proxy+}
    provisionedConcurrency: 1

plugins:
  - serverless-esbuild
custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node20
    platform: node
