@startuml singIn
start
:User enter yours credentials;
:Check the login in the BDD;

if (Login is correct?) then (oui)
  :check the password;
  if (passsword is correct?) then (oui)
    :Send status code 200;
    end
  else (non)
    :Send status code 400;
    :Message "Bad password";
    end
  endif
else (non)
  :Send status code 400;
  :Message "Bad login";
  end
endif

@enduml