apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels: {{.Values.database.label }}
  annotations: {{- toYaml .Values.database.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: {{ .Values.database.service.port }}
      targetPort: 27017
  selector:
    app.kubernetes.io/name: {{ include "mongo.name" . }}