apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.name }}                 # ex: mongodb
  labels: {{- toYaml .Values.database.labels | nindent 4 }}
spec:
  serviceName: {{ .Values.database.name }}          # idem "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: database
    spec:
      securityContext:
        fsGroup: {{ .Values.database.podSecurityContext.fsGroup }}
        fsGroupChangePolicy: {{ .Values.database.podSecurityContext.fsGroupChangePolicy | quote }}

      volumes:
        - name: init-script
          configMap:
            name: mongo-init-script
            defaultMode: 0755

      containers:
        - name: mongo
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}

          ports:
            - containerPort: 27017
              name: mongo

          # credentials root pour que mongo crée l'admin au premier boot
          envFrom:
            - secretRef:
                name: secret-mongo-root

          env:
            # DB initiale à créer. Tu utilises ton configmap hall-e-configmap.DB_NAME.
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: hall-e-configmap
                  key: DB_NAME

            # mot de passe du user applicatif, injecté dans le script d'init
            - name: MONGO_APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mongo-app
                  key: MONGO_APP_USER_PASSWORD
            - name: MONGO_APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-mongo-app
                  key: MONGO_APP_USERNAME

          volumeMounts:
            - name: data
              mountPath: /data/db

            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

          readinessProbe:
            exec:
              command:
                ["sh","-c","mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep -q 1"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            exec:
              command:
                ["sh","-c","mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep -q 1"]
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5

          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.database.persistence.size | quote }}
        {{- if .Values.database.persistence.storageClass }}
        storageClassName: {{ .Values.database.persistence.storageClass | quote }}
        {{- end }}

