export PORT="3000"
export JWT_EXPIRATION=""
export USER_EMAIL=""
export USER_PASSWORD=""
export LOCATIONIQ_API_KEY=""
export SECRET_JWT_KEY=""
export PGUSER=""
export PGPASSWORD=""
export PGHOST="hall-e-postgres"
export PGPORT="5432"
export NODE_ENV="dev"

